In [24]:
import numpy as np
import pandas as pd
from numpy import linalg as la
import math
from sklearn import mixture
dataMatrix=np.loadtxt("clusters.txt",delimiter=",")
g = mixture.GaussianMixture (n_components=3)
g.fit(dataMatrix)
print("Amplitude Of Gaussians")
print("")
print(g.weights_)
print("")
print("Means Of Gaussians")
print("")
print(g.means_)
print("")
print("Covriance of Gaussians")
print("")
print(g.covariances_)



Amplitude Of Gaussians

[ 0.57095326  0.21560803  0.21343871]

Means Of Gaussians

[[-0.96174678 -0.63618636]
 [ 3.2842769   1.9291939 ]
 [ 5.62092993  4.99410684]]

Covriance of Gaussians

[[[ 1.23856256 -0.09316563]
  [-0.09316563  2.02291629]]

 [[ 1.91930032  0.14344635]
  [ 0.14344635  2.57669337]]

 [[ 2.2216601   0.15446244]
  [ 0.15446244  2.094973  ]]]


array([[ -1.86133124e+00,  -2.99168277e+00],
       [ -2.17009237e+00,  -3.29231778e+00],
       [ -1.01408097e+00,   3.85794990e-01],
       [ -2.91294254e+00,  -2.57953917e+00],
       [  3.57207350e-02,  -7.99697919e-01],
       [  2.48350942e+00,   1.55080609e+00],
       [ -5.57616974e-01,   1.84429997e+00],
       [  1.10842255e+00,   3.08907169e+00],
       [  3.62326849e-01,  -2.01912453e+00],
       [  2.70971410e+00,   1.71341276e+00],
       [ -3.54004402e-01,   6.50573081e-01],
       [  6.55103152e-01,   2.50487751e+00],
       [  5.51797714e+00,   4.40317168e-01],
       [  2.56305662e+00,   1.63039337e+00],
       [ -2.08813668e+00,   2.27884440e+00],
       [  2.50393116e+00,  -8.23421912e-01],
       [ -2.06663381e+00,  -9.22130196e-01],
       [  2.21526360e-02,  -2.65809723e+00],
       [  6.47043958e-01,  -1.75000364e-01],
       [  1.94538595e+00,   7.10891971e-01],
       [ -8.88304367e-01,  -1.48627746e+00],
       [  1.20268655e+00,   1.44061369e-01],
       [  